### ISSUE TITLE
Create mixins for RNDOwned

### ISSUE THREAD

**Issue by Master-Foo** [Cabal-Syndicate/randora_framework#16]
If you compare RNDOwned to RNDObject, you'll see it's a hot mess.

Try to copy the file structure of RNDObject and use mixins to separate out the code into individual modules.

Here are some things to note, in case you are not familiar with D packages.

In almost every folder there is going to be a `package.d` file. This is an index for everything in that package.

There will almost always be a file inside a folder with the same name as that folder.

Convention for the properties module naming is as such...

package.d will be named like `module randora.engine.object.properties`

properties.d will be named like `module randora.engine.object.properties.properties` (Notice the redundant 'properties')

Generally speaking, you'd import the package, not the specific file in that package when you want to use something in a package.

It's kind of hard to explain, It's probably best to look at RNDObject and follow it as an example, then ask questions as they come up.

**Comment by Master-Foo** [comment]
BTW... in RNDOwned you'll notice that there are properties that have methods which modify them.

For instance:

`RNDOwned[] slaves = null;`

is modified by 

``` D
void add_slave(RNDOwned slave){
    this.slaves ~= slave;
}
```

the `add_slave` method should go in the Slaves Property mixin. This goes for all "Getters" and "Setters". Any method that modifies a specific variable belongs in the same file as that variable's Property mixin. Why? Because they are tightly bound and can't exist without each other.

An example of this would be in `RNDObject`'s Members property mixin. Look at that for an example.

**Comment by Master-Foo** [comment]
Hey, I'm just checking up on you. I haven't heard back from you since that last commit.

If you have more important stuff to do, that's cool. Work at your own pace. I just thought I'd see if you had any questions or were having any problems.

**Comment by mattwollf** [comment]
No questions yet, just a busy weekend. I have to get around to playing with
dfmt and i will resubmit pull request, and looking at old projects to try
to see if I did something cool with a commit hook that automatically ran a
code formatter.

**Comment by Master-Foo** [comment]
Yeah, that's cool.

Don't worry too much about DFMT, I downloaded it and tried to compile, and something borked. I haven't been able to play around with it enough to get it to work.

If that's something you'd like to explore instead of this grunt work, cool. Otherwise, just be mindful of white space until I can figure it out.

Once I do figure it out, I'll write a script for DUB which automatically checks white space at compile time and fails / fixes if something is wrong. Then, this shouldn't be an issue at all. It's just something that works.

BTW, if you want a project that will get you more familiar with DUB, I have some issues there that a person of your skill level might be interested in. I'll get around to them someday, but right now I need to work on more immediate problems.

For me, the DUB configurations are a chore, but for you they might be something new and interesting to learn.

If you are interested, let me know and I'll make some new issues.

**Comment by Master-Foo** [comment]
OK, I got DFMT to compile.

FYI: If you are running a lot of memory intensive processes (Like Firefox) kill them before you follow the instructions in the README.

My laptop has 4 GB of RAM, but it still borked. So, kill everything first.

I'm going to play around with it and, hopefully, we won't have to worry about white space issues any more.

**Comment by mattwollf** [comment]
Go ahead and create a dub config issue regarding dub configs. I've worked with json before and it doesn't look too crazy, and seems like a decently educational task.

**Comment by Master-Foo** [comment]
Actually, the first thing is going to be converting from json to DUB's new config format, which is more flexible. I'll make an issue tomorrow.
